### ISSUE TITLE
关于您储存库涉及华瑞银行的问题沟通

### ISSUE THREAD

**Issue by yeeton-bj** [modem1024k/streamlit2023#1]
您好，
我们是华瑞银行股份有限公司提供安全服务的厂商-北京亿盾互联科技有限公司。受华瑞银行委托，跟您沟通有关华瑞银行问题。经银行技术部门反馈，您在github上发布的以下4个链接中的内容涉及华瑞银行的关键字或内部代码数据，现在华瑞银行进行护网行动需要删除银行关键信息。请麻烦您删除下此链接相关内容，谢谢配合！
内容链接：
https://github.com/modem1024k/streamlit2023/blob/12968109e558b07bc7935af10a3613b0f7330cfa/hotel.json#L6
![微信截图_20240613092048](https://github.com/modem1024k/streamlit2023/assets/90314410/1c3166c1-35ac-4733-942b-5fc523ee36e8)

**Comment by modem1024k** [comment]
delete all,over
